=== Olesyamir/Banana_Blast/data/xsd/Games.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:g="http://www.univ-grenoble-alpes.fr/l3miage/games"
           targetNamespace="http://www.univ-grenoble-alpes.fr/l3miage/games"
           elementFormDefault="qualified">

    <!-- Définir l'élément racine 'Games' -->
    <xs:element name="Games">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="parties" type="g:Parties"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Type Parties, qui contient une ou plusieurs parties -->
    <xs:complexType name="Parties">
        <xs:sequence>
            <xs:element name="partie" maxOccurs="unbounded" type="g:Partie"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Type Partie, avec les informations de chaque partie -->
    <xs:complexType name="Partie">
        <xs:sequence>
            <xs:element name="nomjoueur" type="xs:string"/>
            <xs:element name="date" type="xs:date"/>
            <xs:element name="score" type="xs:int"/>
            <xs:element name="difficulte" type="xs:string"/>
            <xs:element name="duree" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== Olesyamir/Banana_Blast/data/xml/Games.xml
<?xml version="1.0" encoding="UTF-8"?>
<Games xmlns="http://www.univ-grenoble-alpes.fr/l3miage/games"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.univ-grenoble-alpes.fr/l3miage/games ../xsd/Games.xsd">

    <parties>
        <partie>
            <nomjoueur>John Doe</nomjoueur>
            <date>2024-12-16</date>
            <score>1200</score>
            <difficulte>Hard</difficulte>
            <duree>45 min</duree>
           
        </partie>

        <partie>
            <nomjoueur>John Rami</nomjoueur>
            <date>2024-11-15</date>
            <score>1400</score>
            <difficulte>Medium</difficulte>
            <duree>30 min</duree>
            
        </partie>

        <partie>
            <nomjoueur>John Doe</nomjoueur>
            <date>2024-12-15</date>
            <score>700</score>
            <difficulte>Easy</difficulte>
            <duree>20 min</duree>
        </partie>

        <partie>
            <nomjoueur>John Doe</nomjoueur>
            <date>2021-12-15</date>
            <score>140</score>
            <difficulte>Easy</difficulte>
            <duree>10 min</duree>
        </partie>
    </parties>
</Games>
