=== Olesyamir/Banana_Blast/data/xsd/savedGames.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:jv="http://www.univ-grenoble-alpes.fr/l3miage/jeu_video"
           targetNamespace="http://www.univ-grenoble-alpes.fr/l3miage/jeu_video"
           elementFormDefault="qualified">
    
    
    <!--racine-->
    <xs:element name="savedGames" type="jv:SavedGame"/>

    <!-- Définition du type SavedGame -->
    <xs:complexType name="SavedGame">
        <xs:sequence>
            <xs:element name="parties" type="jv:Parties"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Définition du type Parties -->
    <xs:complexType name="Parties">
        <xs:sequence>
            <xs:element name="partie" type="jv:Partie" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Définition du type Partie -->
    <xs:complexType name="Partie">
        <xs:sequence>
            <xs:element name="nomjoueur" type="xs:string"/>
            <xs:element name="date" type="xs:date"/>
            <xs:element name="score" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>
    
</xs:schema>

=== Olesyamir/Banana_Blast/Data/xml/Parties.xml
<?xml version="1.0" encoding="utf-8"?>
<savedGames xsi:schemaLocation="http://www.univ-grenoble-alpes.fr/l3miage/jeu_video ../xsd/savedGames.xsd" xmlns="http://www.univ-grenoble-alpes.fr/l3miage/jeu_video" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <parties>
    <partie>
      <nomjoueur>John Doe</nomjoueur>
      <date>2024-12-16</date>
      <score>1200</score>
    </partie>
    <partie>
      <nomjoueur>John Rami</nomjoueur>
      <date>2024-11-15</date>
      <score>1400</score>
    </partie>
    <partie>
      <nomjoueur>John Doe</nomjoueur>
      <date>2024-12-15</date>
      <score>700</score>
    </partie>
    <partie>
      <nomjoueur>John Doe</nomjoueur>
      <date>2021-12-15</date>
      <score>140</score>
    </partie>
  </parties>
</savedGames>

=== Olesyamir/Banana_Blast/Data/xml/savedGames.xml
<?xml version="1.0" encoding="UTF-8"?>
<savedGames xmlns="http://www.univ-grenoble-alpes.fr/l3miage/jeu_video" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.univ-grenoble-alpes.fr/l3miage/profile ../xsd/savedGames.xsd">
    
    <parties>
        <partie>
            <nomjoueur>John Doe</nomjoueur>
            <date>2024-12-16</date>
            <score>1200</score>
        </partie>
        
        <partie>
            <nomjoueur>John Rami</nomjoueur>
            <date>2024-11-15</date>
            <score>1400</score>
        </partie>

        <partie>
            <nomjoueur>John Doe</nomjoueur>
            <date>2024-12-15</date>
            <score>700</score>
        </partie>

        <partie>
            <nomjoueur>Reina la reine</nomjoueur>
            <date>2024-11-15</date>
            <score>1400</score>
        </partie>

        <partie>
            <nomjoueur>John Doe</nomjoueur>
            <date>2021-12-15</date>
            <score>140</score>
        </partie>

        <partie>
            <nomjoueur>Dorian</nomjoueur>
            <date>2018-12-15</date>
            <score>10</score>
        </partie>

        <partie>
            <nomjoueur>Marianne</nomjoueur>
            <date>2020-12-15</date>
            <score>340</score>
        </partie>
        

        <partie>
            <nomjoueur>Reina la reine</nomjoueur>
            <date>2019-07-15</date>
            <score>140</score>
        </partie>
        
    </parties>
    
</savedGames>
